# Generated by Django 4.0.1 on 2022-01-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personFirstName', models.CharField(max_length=64)),
                ('personSurName', models.CharField(max_length=64)),
                ('personEmail', models.CharField(max_length=64)),
                ('personPhone', models.CharField(max_length=200)),
                ('personGender', models.CharField(max_length=12)),
            ],
        ),
    ]
