# Generated by Django 4.0.1 on 2022-01-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='personCounter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
