# Generated by Django 4.0.1 on 2022-01-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0002_person_personcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theIp', models.CharField(max_length=70)),
            ],
        ),
    ]
