# Generated by Django 4.0.1 on 2022-01-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0006_alter_person_personemail_alter_person_personsurname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personPhone',
            field=models.IntegerField(max_length=200),
        ),
    ]
