# Generated by Django 4.0.1 on 2022-01-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0007_alter_person_personphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personPhone',
            field=models.IntegerField(),
        ),
    ]
